### ISSUE TITLE
[FE] Implement the Browse Journeys page

### ISSUE THREAD

**Issue by Corgam** [Corgam/SS23_ADSP_TCF#144]
- Similar page to the `View Datasets` panel, a table with all journey objects from the database.
- Should include filtering (the 3-value-filtering, the same as in the `View Datasets` panel, however with a single exception: for the keys, there should be a dropdown menu (as for the operations) with only the "title", "description", "tags", and "author" selectable)
- For each of the journeys, there should be a few buttons: continue the journey, download data, and delete journey (only if you are the author)

**Comment by thdrbrkw** [comment]
This also requires a change of the filter-block component: Create a seperate Input with an array of keys. If the array contains values, the compoent should for the "key"-Field not display a text-input, but rather a dropdown with the passed values. The array should have the following structure: {key: string, displayValue: string}, where key is the key in the data structure, and DisplayValue the visible name in the dropdown in the current language (e.g. "Tags" vs. "Stichworte").

The deletion is allowed for everyone (instead of only the user`s own journies as described in the title)

Endpoints to be used: see Swagger in the Journey-Section

**Comment by Corgam** [comment]
Done #164.
